import streamlit as st
import pandas as pd
from PIL import Image

# Cargar datos
df = pd.read_csv('./Static/Example.csv', sep='!', encoding = "ISO-8859-1")
df = df.sample(n=100, random_state=42) #Seleccionamos las primeras 100 filas y hacemos que se genere aleatoriamente

def main():
    st.title('Curso de uso')
    st.header('Data Science')
    st.write("Data Frame Completo")
    st.dataframe(df, height=150)
    st.write("Data Frame Solo 10 Filas")
    st.dataframe(df.head(10), height=150)
    st.write("Data Frame con Hightlight y maximos")
    st.dataframe(df.style.highlight_max(axis=0), height=150)
    st.write("Data Frame con clasificación de columnas")
    st.write(df.describe())
    st.write("Mostramos un JSON")
    st.json({"clave": "valor"})
    st.write("Mostramos codigo")
    codigo = """
    def hola():
        print("Hola")
    """
    st.code(codigo, language="python")
    st.write("Mostramos un select Box")
    opcion = st.selectbox("Seleccione", ["Opcion 1", "Opcion 2", "Opcion 3"])
    st.write("Opcion seleccionada: ", opcion)
    st.write("------------------------------------------------------------")
    st.write("Mostramos un Multiselect Box")
    opciones = st.multiselect("Seleccione", ["Opcion 1", "Opcion 2", "Opcion 3"])
    st.write(f"Opciones seleccionadas: {opciones}")
    st.write("------------------------------------------------------------")
    st.write("Hacemos un Slider se usa para numeros")
    edad = st.slider("Seleccione su Edad", min_value=10, max_value=100, value=25, step=1)
    st.write("Seleccionaste la Edad: ", edad)
    st.write("------------------------------------------------------------")
    st.write("Hacemos un Select Slider, se usa para categorias strings")
    satisfaccion= st.select_slider("Seleccione tu nivel de satisfacción Edad", options=["Alto", "Medio","Bajo", "Muy Bajo"], value="Medio")
    st.write("Tu nivel de satisfacción es: ", satisfaccion)
    st.write("------------------------------------------------------------")
    st.write("Mostramos una imagen")
    imagen = Image.open("./Static/Screen.png")
    st.image(imagen, use_column_width=True)
    st.write("------------------------------------------------------------")
    st.write("Mostramos una imagen de Internet")
    st.image("https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png")
    st.write("------------------------------------------------------------")
    st.write("Mostramos un video")
    with open("./Static/Ajijos.mp4", "rb") as video_file:
        st.video(video_file.read(), start_time=5)
    st.write("------------------------------------------------------------")
    st.write("Mostramos un audio")
    with open("./Static/Audio1.mp3", "rb") as audio_file:
        st.audio(audio_file.read())
    st.write("------------------------------------------------------------")    
    st.subheader("Tipos de Input")
    st.write("Input Convensional")
    nombre = st.text_input("Ingrese su nombre")
    st.write(nombre)
    st.write("------------------------------------------------------------")
    st.write("Input Tipo Text Area")
    parrafo = st.text_area("Ingrese su nombre", height=100)
    st.write(parrafo)
    st.write("------------------------------------------------------------")
    st.write("Input Tipo Integer")
    numero = st.number_input("Ingrese su nombre", 1.0, 15.0, step=1.0)
    st.write(numero)
    st.write("------------------------------------------------------------")
    st.write("Input Tipo Fecha")
    cita = st.date_input("Ingrese su Fecha de Cumpleaños")
    st.write(cita)
    st.write("------------------------------------------------------------")
    st.write("Input Tipo Hora")
    hora = st.time_input("Ingrese la hora")
    st.write(hora)
    st.write("------------------------------------------------------------")
    st.write("Input Tipo Color Picker")
    color = st.color_picker("Ingrese su color favorito")
    st.write(color)

if __name__=='__main__':
    main()